import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';
import '../models/gps_log.dart';
import '../models/delivery_analytics.dart';

class PdfService {
  Future<void> shareDailyReport(DailyTravelSummary summary) async {
    final pdfBytes = await generateDailyReport(summary);
    final dateStr = DateFormat('yyyy-MM-dd').format(summary.date);
    
    final output = await getTemporaryDirectory();
    final file = File("${output.path}/FieldGPS_Daily_Report_$dateStr.pdf");
    await file.writeAsBytes(pdfBytes);

    await Share.shareXFiles([XFile(file.path)], text: 'Daily Delivery Report - $dateStr');
  }

  Future<Uint8List> generateDailyReport(DailyTravelSummary summary) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd MMM yyyy');
    final timeFormat = DateFormat('hh:mm a');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('DAILY JOURNEY REPORT', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(dateFormat.format(summary.date), style: const pw.TextStyle(fontSize: 16)),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            
            // Stats Grid
            pw.Row(
              children: [
                pw.Expanded(child: _statBox('Total Distance', '${summary.totalDistanceKm.toStringAsFixed(1)} km')),
                pw.SizedBox(width: 10),
                pw.Expanded(child: _statBox('Working Duration', summary.formattedWorkingTime)),
                pw.SizedBox(width: 10),
                pw.Expanded(child: _statBox('Total Deliveries', '${summary.totalDeliveriesCompleted}')),
              ],
            ),
            pw.SizedBox(height: 10),
            pw.Row(
              children: [
                pw.Expanded(child: _statBox('Average Speed', '${summary.averageSpeed.toStringAsFixed(1)} km/h')),
                pw.SizedBox(width: 10),
                pw.Expanded(child: _statBox('Total Stops', '${summary.totalStops}')),
                pw.Expanded(child: pw.SizedBox()), // Empty space for alignment
              ],
            ),
            
            pw.SizedBox(height: 30),
            pw.Text('JOURNEY TIMELINE', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Divider(),
            
            pw.SizedBox(height: 10),
            pw.TableHelper.fromTextArray(
              context: context,
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              cellAlignment: pw.Alignment.centerLeft,
              headers: ['Stop Type', 'Arrival', 'Departure', 'Distance'],
              data: summary.stops.map((stop) => [
                stop.stopType.toUpperCase(),
                timeFormat.format(stop.arrivalTime),
                timeFormat.format(stop.departureTime),
                '${stop.distanceFromPreviousStop.toStringAsFixed(1)} km',
              ]).toList(),
            ),
            
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 40),
              child: pw.Center(
                child: pw.Text('Generated by Field GPS Log App', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
              ),
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }

  pw.Widget _statBox(String label, String value) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
          pw.SizedBox(height: 4),
          pw.Text(value, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  Future<void> generateAndPrintReport(GpsLog log, String vehicleName) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd MMM yyyy, hh:mm a');

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(20),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Driving Log Report',
                    style: pw.TextStyle(
                        fontSize: 24, fontWeight: pw.FontWeight.bold)),
                pw.Divider(),
                pw.SizedBox(height: 10),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Vehicle: $vehicleName'),
                    pw.Text('Date: ${dateFormat.format(log.startTime)}'),
                  ],
                ),
                pw.SizedBox(height: 20),
                pw.Container(
                  padding: const pw.EdgeInsets.all(10),
                  decoration: pw.BoxDecoration(border: pw.Border.all()),
                  child: pw.Column(
                    children: [
                      _row('Total Distance:',
                          '${log.totalDistance.toStringAsFixed(2)} km'),
                      _row('Rate Applied:', 'RS ${log.rateApplied}/km'),
                      pw.Divider(),
                      _row('Total Fare:',
                          'RS ${log.totalFare.toStringAsFixed(2)}',
                          isBold: true),
                    ],
                  ),
                ),
                pw.SizedBox(height: 20),
                pw.Text('Stay Points (Stops)',
                    style: pw.TextStyle(
                        fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 10),
                pw.TableHelper.fromTextArray(
                  headers: ['Arrival', 'Departure', 'Duration'],
                  data: log.stays
                      .map((stay) => [
                            dateFormat.format(stay.arrivalTime!),
                            dateFormat.format(stay.departureTime!),
                            '${stay.durationMinutes} mins',
                          ])
                      .toList(),
                ),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save());
  }

  pw.Widget _row(String label, String value, {bool isBold = false}) {
    final style = pw.TextStyle(
        fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal);
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: style),
          pw.Text(value, style: style),
        ],
      ),
    );
  }
}
